/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
import type { RegistryItem } from "../components/hook-preview"

export const Index: Record<string, RegistryItem> = {
}